name: Deploy Vue App to S3

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      S3_ORIGIN_BUCKET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set execute permission for build.sh
        run: chmod +x ./.github/scripts/build.sh

      - name: Build Vue App
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          CONTENTFUL_ENVIRONMENT: ${{ inputs.CONTENTFUL_ENVIRONMENT }}
          S3_ORIGIN_BUCKET:  "fronted-app-vue"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: "IQoJb3JpZ2luX2VjELP//////////wEaCXVzLXdlc3QtMiJIMEYCIQCjhrAr0mZTQPWQHsDhtuhM09I47jm4DlgXIWkHdXk73QIhAMixFKVHreXxESa/Oj22L+LWzPwve/zj6PzxJr1feH01KrMCCEwQAhoMNzEzMDEwOTY2NDU3Igxerdb/0xJswSxDCvwqkAIl88BsEsFYde6gV6WVu0KX5brcgl/SrNvJa13tC8c6Kwsy+i68yiB4OEU6Wx/uM1mmRauPdspSgOHy54t0Kpx6lg9d49Z0z3p4GqN2EPuUT2O+MKit3oKQpYUFLg85bN7446WriU6g/vIC66JRydFt8eiDAlYVya5xCKljtLr5hKcLM1rAxIHHfUnegKSqKxLU65IAEdxcC4rR/dnIF606SQ213lCHnZ9HsoivCLfwA/IgeC/SNaoijwuow9PLTERQcJBs9VsGI+y13pWYaP+Mn1c7dx2TCmOnqXd+VcDVcuFopxIsIxuDDFl+0THt88gvnXQKFgRL9Mz1irOgImqfXw5+KanOCTPoKccsNpbL3jDu/+i5BjqcAWlpMz4aoJr0bb54/QeVUfamPTVYJ45b3UWVijy12vI6ukxTO909vWmwXLkgNLKc2U/Z8gXPRRjnzVGcE8JWJGY9gkDPUW9XBwIz4/vjfAenFOEFEHw9XvTYFNT+AL1RtaKOcCEtw51kDD8DP/iJAtkZmqAJ7LNoFmiZxGRnEoKJvbU95qkAtmpTEYMWGaIM177MaEUAe3bePUfIMQ=="
          aws-region: "us-east-1"

      - name: Set execute permission for deploy.sh
        run: chmod +x ./.github/scripts/deploy.sh

      - name: S3 Deploy
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          S3_ORIGIN_BUCKET: "fronted-app-vue"