name: Deploy Vue App to S3

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set execute permission for build.sh
        run: chmod +x ./.github/scripts/build.sh

      - name: Build Vue App
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          CONTENTFUL_ENVIRONMENT: ${{ inputs.CONTENTFUL_ENVIRONMENT }}
          S3_ORIGIN_BUCKET: ${{ github.ref == 'refs/heads/main' && 'german-fronted-app-main' || github.ref == 'refs/heads/dev' && 'german-fronted-app-dev' || 'german-fronted-app-test' }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set execute permission for deploy.sh
        run: chmod +x ./.github/scripts/deploy.sh

      - name: S3 Deploy
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          S3_ORIGIN_BUCKET: ${{ github.ref == 'refs/heads/main' && 'german-fronted-app-main' || github.ref == 'refs/heads/dev' && 'german-fronted-app-dev' || 'german-fronted-app-test' }}
