name: Github Action Workflow PROD

on:
  push:
    branches:
      - main
      - dev
      - test
  repository_dispatch:
    types:
      - build-prod
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine S3 bucket
        id: get-bucket
        run: echo "bucket=$(case ${{ github.ref_name }} in
                            main) echo 'german-fronted-app-main';;
                            dev) echo 'german-fronted-app-dev';;
                            test) echo 'german-fronted-app-test';;
                          esac)" >> $GITHUB_ENV

      - name: Deploy to S3
        uses: ./.github/workflows/deploy-to-s3.yml
        with:
          CI_ENV: ${{ github.ref_name }}
          CONTENTFUL_ENVIRONMENT: ${{ github.ref_name }}
          S3_ORIGIN_BUCKET: ${{ env.bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: "us-east-1"
